# Generated by Django 5.2.6 on 2025-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='find_out',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('buy', 'Buy a bike'), ('sell', 'Sell a bike'), ('support', 'Customer Support'), ('other', 'Other')], max_length=20),
        ),
    ]
