# Generated by Django 5.2.6 on 2025-09-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('model', models.CharField(default='Unknown Model', max_length=100)),
                ('specs', models.CharField(blank=True, default='', max_length=255)),
                ('mileage', models.IntegerField(default=0)),
                ('owner', models.CharField(default='Unknown Owner', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('location', models.CharField(default='Unknown Location', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes/')),
                ('brand', models.CharField(default='Unknown Brand', max_length=50)),
                ('fuel', models.CharField(default='Petrol', max_length=20)),
                ('category', models.CharField(default='Motorcycle', max_length=50)),
                ('color', models.CharField(default='Unknown', max_length=50)),
                ('booked', models.BooleanField(default=False)),
                ('specs_json', models.JSONField(blank=True, default=dict)),
                ('overview', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
