# Generated by Django 5.2.6 on 2025-09-11 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='specs_json',
        ),
        migrations.AddField(
            model_name='bike',
            name='chassis_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='insurance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='registration_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='service_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bike',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bikes/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.bike')),
            ],
        ),
    ]
